name: doris_downloader
description: "Video downloader for my mom."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  another_flushbar: ^1.12.32
  chewie: ^1.13.0
  dio: ^5.9.0
  easy_image_viewer: ^1.5.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.0
  flutter_sharing_intent: ^1.1.1
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  icons_launcher: ^3.0.3
  json_annotation: ^4.9.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/